#import "./fragments.gql"


mutation loginUser($login: String!, $password: String!) {
  loginUser(login: $login, password:$password) {
    ...Resolver
  }
}

mutation registerUser($login: String!, $password: String!) {
  createUser(login: $login, password:$password) {
    ...Resolver
  }
}