mutation($login: String!, $password: String!) {
  loginUser(login: $login, password:$password) {
    status
    error {
      code
    }
  }
  createUser(login: $login, password:$password) {
    status
    error {
      code
    }
  }
}